import { Courier_Prime, Inter } from "next/font/google";
import "./globals.css";

const courier = Courier_Prime({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="container">
      <body className={courier.className}>
        {/* <Navbar /> */}
        {children}
        <br />
        </body>
        </div>
    </html>
  );
}
